apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "namecom-webhook.fullname" . }}
  labels:
    app: {{ include "namecom-webhook.name" . }}
    chart: {{ include "namecom-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
# Grant permissions to read secrets inside the cluster to allow to have issuer in another namespace than the webhook
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "namecom-webhook.fullname" . }}:secrets-reader
  labels:
    app: {{ include "namecom-webhook.name" . }}
    chart: {{ include "namecom-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
rules:
  - apiGroups:
      - ''
    resources:
      - 'secrets'
    verbs:
      - 'get'
---
# Bind the previously created role to the webhook service account to allow reading from secrets in all namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "namecom-webhook.fullname" . }}:secrets-reader
  labels:
    app: {{ include "namecom-webhook.name" . }}
    chart: {{ include "namecom-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "namecom-webhook.fullname" . }}:secrets-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "namecom-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "namecom-webhook.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: {{ include "namecom-webhook.name" . }}
    chart: {{ include "namecom-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "namecom-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "namecom-webhook.fullname" . }}:auth-delegator
  labels:
    app: {{ include "namecom-webhook.name" . }}
    chart: {{ include "namecom-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "namecom-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "namecom-webhook.fullname" . }}:domain-solver
  labels:
    app: {{ include "namecom-webhook.name" . }}
    chart: {{ include "namecom-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "namecom-webhook.fullname" . }}:domain-solver
  labels:
    app: {{ include "namecom-webhook.name" . }}
    chart: {{ include "namecom-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "namecom-webhook.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "namecom-webhook.fullname" . }}:flowcontrol-solver
  labels:
    app: {{ include "namecom-webhook.name" . }}
    chart: {{ include "namecom-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - 'flowcontrol.apiserver.k8s.io'
    resources:
      - 'prioritylevelconfigurations'
      - 'flowschemas'
    verbs:
      - 'list'
      - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "namecom-webhook.fullname" . }}:flowcontrol-solver
  labels:
    app: {{ include "namecom-webhook.name" . }}
    chart: {{ include "namecom-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "namecom-webhook.fullname" . }}:flowcontrol-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "namecom-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
